---

- name: install nginx related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - nginx
  tags:
    - nginx
    - install

# Assumes wildcard SSL if using local storage.
- name: copy canvas ssl pem file
  copy: src='etc/ssl/certs/canvas.pem' dest='/etc/ssl/certs/canvas.pem' owner=root group=root mode=644
  tags:
    - nginx
    - install

# Assumes wildcard SSL if using local storage.
- name: copy canvas ssl key file
  copy: src='etc/ssl/private/canvas.key' dest='/etc/ssl/private/canvas.key' owner=root group=ssl-cert mode=640
  tags:
    - nginx
    - install

- name: remove default nginx sites
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx service
  tags:
    - nginx
    - configure

- name: configure canvas nginx site
  template: src=etc/nginx/sites-available/canvas.j2 dest=/etc/nginx/sites-available/canvas
  notify: restart nginx service
  tags:
    - nginx
    - configure
