---

- name: apt update
  apt: update_cache=yes
  tags:
    - common
    - apt

- name: apt upgrade
  apt: upgrade=dist
  tags:
    - common
    - apt

- name: reboot host
  command: /sbin/shutdown -r now
  tags:
    - common
    - apt

- name: wait for host to be down
  sudo: false
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  tags:
    - common
    - apt

- name: wait for host to be up
  sudo: false
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
  tags:
    - common
    - apt

- name: install git-core
  apt: pkg=git-core state=latest
  tags:
    - common
    - git

- name: install ntp
  apt: pkg=ntp state=latest
  tags:
    - common
    - ntp

- name: setup ntp configuration
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp service
  tags:
    - common
    - ntp

- name: install iptables-persistent
  apt: pkg=iptables-persistent state=latest
  tags:
    - common
    - iptables
    - secure

- name: setup iptables-persistent rules
  template: src=etc/iptables/rules.v4.j2 dest=/etc/iptables/rules.v4
  notify: reload iptables-persistent service
  tags:
    - common
    - iptables
    - secure

- name: setup interfaces
  template: src=etc/network/interfaces.j2 dest=/etc/network/interfaces
  notify: restart networking service
  tags:
    - common
    - interfaces

- name: setup ssh configuration
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh service
  tags:
    - common
    - ssh
    - secure

- name: setup sysctl configuration
  template: src=etc/sysctl.conf.j2 dest=/etc/sysctl.conf
  notify: reload sysctl configuration
  tags:
    - common
    - sysctl
    - secure

- name: secure /usr/local/bin
  file: state=directory path=/usr/local/bin mode=0711 owner=root group=root recurse=yes
  tags:
    - common
    - secure

- name: secure /etc
  file: state=directory path=/etc mode=0711
  tags:
    - common
    - secure

- name: secure /tmp
  file: state=directory path=/tmp mode=1777 recurse=yes
  tags:
    - common
    - secure

- name: secure /var/tmp
  file: state=directory path=/var/tmp mode=1777 recurse=yes
  tags:
    - common
    - secure
