---

- name: install redis related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - redis-server
  tags:
    - redis
    - install

- name: configure redis
  template: src=etc/redis/redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis service
  tags:
    - redis
    - configure
