---

- name: install general library packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - imagemagick
     - libcurl4-gnutls-dev
     - libpq5
     - libpq-dev
     - libxml2-dev
     - libxmlsec1
     - libxmlsec1-dev
     - libxslt1-dev
     - unzip
     - zlib1g-dev
  tags:
    - application
    - library

- name: install python related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - python
     - python-software-properties
  tags:
    - application
    - python

- name: install java related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-7-jre
  tags:
    - application
    - java

- name: install ruby related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - ruby1.9.1
     - ruby1.9.1-dev
     - ruby-httpclient
     - ruby-passenger
  tags:
    - application
    - ruby

- name: install javascript related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - nodejs
     - coffeescript
  tags:
    - application
    - javascript

- name: install apache related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - apache2
     - libapache2-mod-passenger
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: enable apache rewrite mod
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: enable apache passenger mod
  command: a2enmod passenger creates=/etc/apache2/mods-enabled/passenger.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: check if canvas is installed
  stat: path=/var/canvas
  register: canvas_installed
  tags:
    - application
    - canvas

- name: git clone canvas stable branch
  git:
    repo=https://github.com/instructure/canvas-lms.git
    dest=/var/canvas
    version=stable
    update=no
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: create /var/canvas/log
  file: path=/var/canvas/log state=directory
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: create /var/canvas/tmp/pids
  file: path=/var/canvas/tmp/pids state=directory
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: create /var/canvas/public/assets
  file: path=/var/canvas/public/assets state=directory
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: create /var/canvas/public/stylesheets/compiled
  file: path=/var/canvas/public/stylesheets/compiled state=directory
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: create /var/canvas/Gemfile.lock
  file: path=/var/canvas/Gemfile.lock state=touch
  when: not canvas_installed.stat.exists
  tags:
    - application
    - canvas

- name: check if canvas gems are installed
  stat: path=/var/canvas/vendor/bundle
  register: canvas_gems_installed
  tags:
    - application
    - canvas

- name: install bundler gem
  command: gem install bundler --version=1.5.3
  when: not canvas_gems_installed.stat.exists
  tags:
    - application
    - canvas

- name: install canvas gems
  command: chdir=/var/canvas bundle install --path vendor/bundle --without=sqlite mysql development test
  when: not canvas_gems_installed.stat.exists
  tags:
    - application
    - canvas

- name: secure /var/canvas
  file: path=/var/canvas state=directory owner=canvas group=canvas mode=0700 recurse=yes
  tags:
    - application
    - canvas
    - secure

- name: secure /var/canvas/config
  file: path=/var/canvas/config state=directory owner=canvas group=canvas mode=0400 recurse=yes
  tags:
    - application
    - canvas
    - secure
