---

- name: install general library packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - imagemagick
     - libcurl4-gnutls-dev
     - libpq5
     - libpq-dev
     - libxml2-dev
     - libxmlsec1
     - libxmlsec1-dev
     - libxslt1-dev
     - zlib1g-dev
  tags:
    - application
    - library

- name: install python related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - python
     - python-software-properties
  tags:
    - application
    - python

- name: install java related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-7-jre
  tags:
    - application
    - java

- name: install ruby related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - ruby1.9.1
     - ruby1.9.1-dev
     - ruby-httpclient
     - ruby-passenger
  tags:
    - application
    - ruby

- name: install bundler gem
  gem: name=bundler state=latest user_install=no
  tags:
    - application
    - ruby

- name: install javascript related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - nodejs
     - coffeescript
  tags:
    - application
    - javascript

- name: install apache related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - apache2
     - libapache2-mod-passenger
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: enable apache rewrite mod
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: enable apache passenger mod
  command: a2enmod passenger creates=/etc/apache2/mods-enabled/passenger.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - application
    - apache

- name: create canvas directory
  file: path=/usr/local/bin/canvas state=directory owner=canvas group=canvas mode=0700
  tags:
    - application
