---

- name: install apache related packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
     - apache2
     - libapache2-mod-passenger
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - apache

- name: enable apache rewrite mod
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - apache

- name: enable apache passenger mod
  command: a2enmod passenger creates=/etc/apache2/mods-enabled/passenger.load
  notify: restart apache service
  when: jobs_only is not defined or not jobs_only|bool
  tags:
    - apache
