---

- include: application.yml
- include: cache.yml
- include: database-pool-coordinator.yml
- include: database-pool-master.yml
- include: database-pool-slave.yml
- include: database-standy-master.yml
- include: database-standy-slave.yml
- include: database-xc-coordinator.yml
- include: database-xc-datanode.yml
- include: database-xc-gtm.yml
- include: proxy.yml
